language: node_js
#指定nodejs版本，可以指定多个
node_js:
  - 4.4.4

#运行的脚本命令
script:
  - npm --harmony index.js

#数据库
services:
  - mysql

test:
  database: 3dweb
  username: root
  encoding: utf8

before_script:
  - mysql -e "create database IF NOT EXISTS 3dweb;"

before_install:
  - mysql -e "create database IF NOT EXISTS 3dweb;" -uroot

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master